name: Delete All Runs
on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete all runs
        run: |
          gh run list --json databaseId -q '.[].databaseId' | xargs -I {} gh run delete {} --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
